import { MerchantWorkspace, Storefront } from "./types";

export const storefronts: Storefront[] = [
  {
    slug: "a3-official",
    displayName: "A3! Official Store",
    gameTitle: "A3! (Act! Addict! Actors!)",
    logo:
      "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=200&q=80",
    heroImage:
      "https://images.unsplash.com/photo-1500534319109-2f56fabc3302?auto=format&fit=crop&w=1600&q=80",
    tagline: "Limited Fest · Manga Remix",
    highlightSlogan: "Extra diamonds + character frames",
    summary:
      "Collab event store with anime storyboard backgrounds, autograph cards, and PayPay-ready checkout for Japanese fans.",
    companyName: "Liber Entertainment Inc.",
    contactEmail: "support@a3-app.jp",
    supportChannel: "Discord & in-app ticket",
    storefrontUrl: "https://pay.waffo.jp/store/a3-official",
    primaryColor: "#ff6699",
    paymentMethods: ["Visa", "Mastercard", "JCB", "PayPay", "Apple Pay"],
    features: ["App Pay exclusive", "Webhook under 2s", "Instant PayPay cashback"],
    userIdentifierLabel: "Game ID",
    userIdentifierHint: "Example: A3-7821-9933",
    legalLinks: [
      { label: "Legal disclosure", url: "https://a3.jp/legal/act" },
      { label: "Payment services act", url: "https://a3.jp/legal/payment" },
      { label: "Terms of service", url: "https://a3.jp/terms" },
      { label: "Privacy policy", url: "https://a3.jp/privacy" },
      { label: "Cancellation & refund", url: "https://a3.jp/cancel" },
    ],
    products: [
      {
        id: "pack-limited-01",
        name: "Full Bloom Celebration Pack",
        category: "Limited pack",
        price: 10000,
        currency: "JPY",
        baseAmount: 820,
        bonusAmount: 120,
        description: "Anniversary art + 820 diamonds with 120 bonus",
        icon: "https://images.unsplash.com/photo-1520974798311-35179017a9d8?w=400",
        gameItemId: "A3_PACK_LIMITED",
        limited: true,
        promotion: {
          type: "bonus",
          value: 18,
          copy: "18% better than in-game",
          badge: "Limited",
          highlight: "App Pay exclusive pack!!",
        },
      },
      {
        id: "pack-regular-02",
        name: "Diamond 720",
        category: "Standard top-up",
        price: 8000,
        currency: "JPY",
        baseAmount: 720,
        bonusAmount: 60,
        description: "Regular charge with +60 bonus",
        icon: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
        gameItemId: "A3_DIA_720",
        promotion: {
          type: "bonus",
          value: 9,
          copy: "9% bonus",
        },
      },
      {
        id: "pack-mini-03",
        name: "Starter Pack",
        category: "Special bundle",
        price: 3000,
        currency: "JPY",
        baseAmount: 250,
        bonusAmount: 30,
        description: "Beginner items plus 30 bonus diamonds",
        icon: "https://images.unsplash.com/photo-1512499617640-c2f999098c01?w=400",
        gameItemId: "A3_STARTER",
        promotion: {
          type: "bonus",
          value: 12,
          copy: "12% bonus",
        },
      },
    ],
    filters: {
      categoryTags: ["App Pay exclusive", "Bonus >10%"],
      minBonusPercent: 10,
      exclusive: true,
    },
  },
  {
    slug: "stella-stage",
    displayName: "Stella Stage Exchange",
    gameTitle: "Stella Stage Online",
    logo:
      "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=200&q=80",
    heroImage:
      "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1600",
    tagline: "Galaxy Expedition: Neon Act",
    highlightSlogan: "Crystals 10% cheaper than in-game",
    summary:
      "Comic-style control room with season pass rewards, neon cockpit frames, and Line Pay installments for space idols.",
    companyName: "Stella Interactive Limited",
    contactEmail: "ops@stella-stage.com",
    supportChannel: "Slack Connect",
    storefrontUrl: "https://pay.waffo.jp/store/stella-stage",
    primaryColor: "#7c5dff",
    paymentMethods: ["Visa", "Mastercard", "AMEX", "Line Pay", "Konbini"],
    features: ["Subscription ready", "Automatic webhook retries", "Installment support"],
    userIdentifierLabel: "Pilot ID",
    userIdentifierHint: "ST-8891-XXXX",
    legalLinks: [
      { label: "Legal disclosure", url: "https://stella-stage.com/legal/tokusho" },
      { label: "Payment services act", url: "https://stella-stage.com/legal/fund" },
      { label: "Terms of service", url: "https://stella-stage.com/terms" },
      { label: "Privacy policy", url: "https://stella-stage.com/privacy" },
      { label: "Cancellation", url: "https://stella-stage.com/cancel" },
    ],
    products: [
      {
        id: "stella-season",
        name: "Season Flight Pass",
        category: "Limited pack",
        price: 12000,
        currency: "JPY",
        baseAmount: 1,
        description: "12 weeks of elite missions + bonus drops",
        gameItemId: "ST_PASS_LUX",
        subscription: true,
        promotion: {
          type: "bonus",
          value: 25,
          copy: "25% faster progress",
          badge: "Season",
        },
      },
      {
        id: "stella-crystal",
        name: "Crystal 1500",
        category: "Standard top-up",
        price: 10000,
        currency: "JPY",
        baseAmount: 1500,
        promotion: {
          type: "discount",
          value: 10,
          copy: "10% OFF",
          highlight: "Cheaper than in-game",
        },
        description: "Large update launch discount",
        gameItemId: "ST_CRYS_1500",
      },
      {
        id: "stella-kit",
        name: "Mechanic Kit",
        category: "Supply",
        price: 4500,
        currency: "JPY",
        baseAmount: 340,
        bonusAmount: 40,
        description: "Weekly materials + 40 crystals",
        gameItemId: "ST_SUPPORT",
      },
    ],
    filters: {
      categoryTags: ["App Pay exclusive", "Subscription"],
      minBonusPercent: 5,
    },
  },
  {
    slug: "mirage-saga",
    displayName: "Mirage Saga Lab",
    gameTitle: "Mirage Saga Reversal",
    logo:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=200&q=80",
    heroImage:
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1600&q=80",
    tagline: "Deep Realm Anime Drop",
    highlightSlogan: "App Pay limited gear bundles",
    summary:
      "Designed like a manga ops room: PayPay + Google Pay routes, 99.99% webhook success, and holographic avatar skins.",
    companyName: "Mirage Digital GK",
    contactEmail: "merchant@mirage.io",
    supportChannel: "Email + PagerDuty",
    storefrontUrl: "https://pay.waffo.jp/store/mirage-saga",
    primaryColor: "#11b0a5",
    paymentMethods: ["Visa", "Mastercard", "PayPay", "Google Pay", "Konbini"],
    features: ["5x webhook retries", "PayPay accepted", "15% better than game"],
    userIdentifierLabel: "User Code",
    userIdentifierHint: "MG-XXXX-00",
    legalLinks: [
      { label: "Legal disclosure", url: "https://mirage.io/tokusho" },
      { label: "Payment services act", url: "https://mirage.io/fund" },
      { label: "Terms of service", url: "https://mirage.io/terms" },
      { label: "Privacy policy", url: "https://mirage.io/privacy" },
      { label: "Return policy", url: "https://mirage.io/cancel" },
    ],
    products: [
      {
        id: "mirage-bundle-top",
        name: "Deep Gear Advance",
        category: "Limited pack",
        price: 14000,
        currency: "JPY",
        baseAmount: 1600,
        bonusAmount: 300,
        gameItemId: "MG_ADV_PACK",
        description: "Gear upgrade mats + 15% crystal boost",
        promotion: {
          type: "bonus",
          value: 15,
          copy: "15% bonus",
          highlight: "Eligible for PayPay cashback",
        },
      },
      {
        id: "mirage-monthly",
        name: "Monthly Supply Plan",
        category: "Subscription",
        price: 3200,
        currency: "JPY",
        baseAmount: 1,
        subscription: true,
        description: "30-day plan with +60 crystals per day",
        gameItemId: "MG_MONTHLY",
      },
      {
        id: "mirage-core",
        name: "Core Charge 980",
        category: "Standard top-up",
        price: 9800,
        currency: "JPY",
        baseAmount: 980,
        bonusAmount: 80,
        description: "8% more crystals via App Pay",
        gameItemId: "MG_CORE_980",
        promotion: {
          type: "bonus",
          value: 8,
          copy: "8% bonus",
        },
      },
    ],
    filters: {
      categoryTags: ["PayPay supported", "Webhook 99.99"],
      minBonusPercent: 8,
    },
  },
  {
    slug: "idol-rhythm-lab",
    displayName: "Idol Rhythm Lab",
    gameTitle: "Starbeat!!",
    logo:
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=200&q=80",
    heroImage:
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=80",
    tagline: "City Pop Encore",
    highlightSlogan: "Fanboxes + 2x sticker packs",
    summary:
      "Idol gacha storefront featuring rhythm skins, meet & greet passes, and Line Pay instalments for JP fans.",
    companyName: "Idol Rhythm Studio",
    contactEmail: "support@idol-rhythm.jp",
    supportChannel: "Discord + Twitter DM",
    storefrontUrl: "https://pay.waffo.jp/store/idol-rhythm-lab",
    primaryColor: "#f472b6",
    paymentMethods: ["Visa", "Mastercard", "Line Pay", "PayPay", "Konbini"],
    features: ["Sticker fanboxes", "Line Pay instalments", "Live data feed"],
    userIdentifierLabel: "Producer ID",
    userIdentifierHint: "SB-2024-XXXX",
    legalLinks: [
      { label: "Legal disclosure", url: "https://idol-rhythm.jp/legal" },
      { label: "Payment services act", url: "https://idol-rhythm.jp/payment" },
      { label: "Terms", url: "https://idol-rhythm.jp/terms" },
      { label: "Privacy", url: "https://idol-rhythm.jp/privacy" },
      { label: "Cancellation", url: "https://idol-rhythm.jp/cancel" },
    ],
    products: [
      {
        id: "idol-fanbox",
        name: "Fanbox MAX",
        category: "Limited pack",
        price: 9500,
        currency: "JPY",
        baseAmount: 1000,
        bonusAmount: 180,
        description: "City pop frame + chibi stickers + 18% extra gems",
        icon: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400",
        gameItemId: "SB_FANBOX_MAX",
        promotion: {
          type: "bonus",
          value: 18,
          copy: "18% bonus",
        },
      },
      {
        id: "idol-pass",
        name: "Encore Pass (30d)",
        category: "Subscription",
        price: 3600,
        currency: "JPY",
        baseAmount: 1,
        description: "Daily mic fragments + backstage missions",
        gameItemId: "SB_ENCORE_PASS",
        subscription: true,
      },
      {
        id: "idol-quick",
        name: "Ruby 480",
        category: "Standard top-up",
        price: 4800,
        currency: "JPY",
        baseAmount: 480,
        bonusAmount: 40,
        description: "Includes 40 fanclub bonus rubies",
        gameItemId: "SB_RUBY_480",
      },
    ],
    filters: {
      categoryTags: ["App Pay exclusive", "Subscription"],
      minBonusPercent: 15,
    },
  },
  {
    slug: "shinobi-remix",
    displayName: "Shinobi Remix",
    gameTitle: "Ninja Rewrite Online",
    logo:
      "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=200&q=80",
    heroImage:
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=80",
    tagline: "Stealth Ops Reloaded",
    highlightSlogan: "Camo skins + weapon shards",
    summary:
      "A neon dojo storefront delivering stealth operators, weapon shards, and Google Pay friendly checkout.",
    companyName: "Kurome Interactive",
    contactEmail: "ops@shinobi-remix.jp",
    supportChannel: "PagerDuty + Slack",
    storefrontUrl: "https://pay.waffo.jp/store/shinobi-remix",
    primaryColor: "#0ea5e9",
    paymentMethods: ["Visa", "Mastercard", "Google Pay", "PayPay", "Konbini"],
    features: ["Webhook auto-retry", "3D camo previews", "PayPay boost"],
    userIdentifierLabel: "Shinobi Code",
    userIdentifierHint: "SR-XX-0000",
    legalLinks: [
      { label: "Legal disclosure", url: "https://shinobi-remix.jp/legal" },
      { label: "Payment services act", url: "https://shinobi-remix.jp/payment" },
      { label: "Terms", url: "https://shinobi-remix.jp/terms" },
      { label: "Privacy", url: "https://shinobi-remix.jp/privacy" },
      { label: "Cancellation", url: "https://shinobi-remix.jp/cancel" },
    ],
    products: [
      {
        id: "shinobi-camo",
        name: "Neon Camo Arsenal",
        category: "Limited pack",
        price: 11000,
        currency: "JPY",
        baseAmount: 1200,
        bonusAmount: 220,
        description: "Operator skin + 220 shard bonus",
        icon: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=400",
        gameItemId: "SR_CAMO",
        promotion: {
          type: "bonus",
          value: 22,
          copy: "22% bonus",
        },
      },
      {
        id: "shinobi-core",
        name: "Kunai Core 980",
        category: "Standard top-up",
        price: 9800,
        currency: "JPY",
        baseAmount: 980,
        description: "Standard charge for fast rerolls",
        gameItemId: "SR_CORE_980",
      },
    ],
    filters: {
      categoryTags: ["PayPay supported", "Bonus >20%"],
      minBonusPercent: 20,
    },
  },
  {
    slug: "cyber-drift-garage",
    displayName: "Cyber Drift Garage",
    gameTitle: "Hyper Drift: Neon",
    logo:
      "https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?auto=format&fit=crop&w=200&q=80",
    heroImage:
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=80",
    tagline: "Street Festival Drop",
    highlightSlogan: "Blueprints + boost chips",
    summary:
      "Cyberpunk garage offering drift blueprints, glow rims, and Konbini-friendly checkout with webhook analytics.",
    companyName: "Neon Torque Labs",
    contactEmail: "garage@cyber-drift.jp",
    supportChannel: "Telegram + Email",
    storefrontUrl: "https://pay.waffo.jp/store/cyber-drift-garage",
    primaryColor: "#f97316",
    paymentMethods: ["Visa", "Mastercard", "AMEX", "Konbini", "PayPay"],
    features: ["Blueprint bundles", "Webhook analytics", "Konbini ready"],
    userIdentifierLabel: "Driver Tag",
    userIdentifierHint: "HDN-0042",
    legalLinks: [
      { label: "Legal disclosure", url: "https://cyber-drift.jp/legal" },
      { label: "Payment services act", url: "https://cyber-drift.jp/payment" },
      { label: "Terms", url: "https://cyber-drift.jp/terms" },
      { label: "Privacy", url: "https://cyber-drift.jp/privacy" },
      { label: "Cancellation", url: "https://cyber-drift.jp/cancel" },
    ],
    products: [
      {
        id: "drift-glow-pack",
        name: "Glow Drift Pack",
        category: "Limited pack",
        price: 12500,
        currency: "JPY",
        baseAmount: 1500,
        bonusAmount: 250,
        description: "Neon rims + 250 boost chips",
        icon: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=400",
        gameItemId: "HDN_GLOW",
        promotion: {
          type: "bonus",
          value: 20,
          copy: "20% bonus",
        },
      },
      {
        id: "drift-pass",
        name: "Street Season Pass",
        category: "Subscription",
        price: 4200,
        currency: "JPY",
        baseAmount: 1,
        description: "4-week challenge ladder + sponsor missions",
        gameItemId: "HDN_PASS",
        subscription: true,
      },
    ],
    filters: {
      categoryTags: ["Blueprint bundles", "Subscription"],
      minBonusPercent: 20,
    },
  },
];

export const merchantWorkspace: MerchantWorkspace = {
  store: storefronts[0],
  webhook: {
    url: "https://hooks.a3-app.jp/v1/order",
    secret: "whsec_live_x2vy-merchant",
    userIdField: "gameId",
    retries: 3,
    lastLatencyMs: 1480,
    reliability: 99.995,
    lastDeliveryAt: new Date().toISOString(),
  },
  settlement: {
    bankName: "MUFG Bank",
    accountName: "Liber Entertainment",
    accountNumber: "1234567",
    branch: "Shibuya Central",
    currency: "JPY",
    payoutSchedule: "T+5 rolling",
    status: "verified",
  },
  lastPublish: "2025-11-08T15:30:00+09:00",
};

export const paymentFilters = [
  { label: "App Pay exclusive", value: "exclusive" },
  { label: "Bonus > 10%", value: "bonus10" },
  { label: "PayPay supported", value: "paypay" },
];

export function getStorefronts(): Storefront[] {
  return storefronts;
}

export function getStorefrontBySlug(slug: string): Storefront | undefined {
  return storefronts.find((store) => store.slug === slug);
}
